### ISSUE TITLE
Save temp snapshots in temp dir

### ISSUE THREAD

**Issue by rugk** [milkey-mouse/backup-vm#2]
That does not look good:

https://github.com/milkey-mouse/backup-vm/blob/12b57ffe032fc4637ecf0f243c9004dceff987d5/backup-vm.py#L365-L367

Would not it be better if backups are saved in the temp dir (`/tmp`), which is usually intended for that purpose?

**Comment by milkey-mouse** [comment]
On many systems the `/tmp` dir is mounted, well, temporarily, with the contents being deleted on reboot or other events. I want the snapshot disk images to be persistent and on an actual hard drive (which the default libvirt location almost always is), so that if the computer has an unexpected shutdown or there is another error that prevents the disks from merging, it can still run from the snapshot upon reboot. Then the user could manually `virsh blockcommit` after recovering from an error (which I should make a wiki article for...)

**Comment by rugk** [comment]
Okay, that's a valid argument.
